import os
import google.generativeai as genai
import base64
from io import BytesIO
from PIL import Image

async def enhance_image(image_bytes, prompt):
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        print("Error: GOOGLE_API_KEY not found.")
        return None

    genai.configure(api_key=api_key)
    
    # Using Imagen 3 model
    # Note: As of late 2024, the model name might be 'imagen-3.0-generate-001' or similar.
    # We will try the standard 'imagen-3.0-generate-001'.
    try:
        model = genai.ImageGenerationModel("imagen-3.0-generate-001")
        
        # Since Imagen is T2I, we use the prompt generated by the analysis step.
        # We add "photorealistic product photography" to ensure style.
        full_prompt = f"Professional product photography. {prompt}. High resolution, 8k, studio lighting."

        response = model.generate_images(
            prompt=full_prompt,
            number_of_images=1,
            aspect_ratio="1:1", # Assuming square for now, or we could detect.
            safety_filter_level="block_only_high",
            person_generation="allow_adult",
        )
        
        if response.images:
            # Convert PIL Image to Base64
            image = response.images[0]
            buffered = BytesIO()
            image.save(buffered, format="PNG")
            return base64.b64encode(buffered.getvalue()).decode("utf-8")
        else:
            print("Imagen returned no images.")
            return None

    except Exception as e:
        print(f"Imagen Service Exception: {e}")
        # Fallback for testing if model not found/access denied (common with new models)
        return None
